export const dummyData = [
  { name: "Emma Brown", email: "emma.brown@example.com", age: 27 },
  { name: "Neha", email: "neha@example.com", age: 28 },
  { name: "Lisa Martin", email: "lisa.martin@example.com", age: 29 },
  { name: "Shivang", email: "shivang@example.com", age: 30 },
  { name: "Alice Smith", email: "alice.smith@example.com", age: 32 },
  { name: "Susan Green", email: "susan.green@example.com", age: 33 },
  { name: "John Doe", email: "john.doe@example.com", age: 35 },
  { name: "David White", email: "david.white@example.com", age: 38 },
  { name: "Bob Jones", email: "bob.jones@example.com", age: 40 },
  { name: "Michael Williams", email: "michael.williams@example.com", age: 45 },
  { name: "Shivang", email: "shivang@example.com", age: 30 },
  { name: "Alice Smith", email: "alice.smith@example.com", age: 32 },
  { name: "Susan Green", email: "susan.green@example.com", age: 33 },
  { name: "John Doe", email: "john.doe@example.com", age: 35 },
  { name: "David White", email: "david.white@example.com", age: 38 },
  { name: "Bob Jones", email: "bob.jones@example.com", age: 40 },
  { name: "Michael Williams", email: "michael.williams@example.com", age: 45 },
  { name: "Shivang", email: "shivang@example.com", age: 30 },
  { name: "Alice Smith", email: "alice.smith@example.com", age: 32 },
  { name: "Susan Green", email: "susan.green@example.com", age: 33 },
  { name: "John Doe", email: "john.doe@example.com", age: 35 },
  { name: "David White", email: "david.white@example.com", age: 38 },
  { name: "Bob Jones", email: "bob.jones@example.com", age: 40 },
  { name: "Michael Williams", email: "michael.williams@example.com", age: 45 }
];
